# Generated by Django 2.0 on 2018-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('DT', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
    ]
