# Generated by Django 2.0 on 2018-09-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_er_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='er_test',
            table='test',
        ),
    ]
