# Generated by Django 2.0 on 2018-09-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180925_1016'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='er_test',
            table='er_test',
        ),
    ]
