# Generated by Django 2.0 on 2018-10-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180925_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bed', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'abnormalroom',
            },
        ),
        migrations.CreateModel(
            name='av',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bed', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'availableroom',
            },
        ),
        migrations.CreateModel(
            name='oc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bed', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'occupiedroom',
            },
        ),
    ]
