# Generated by Django 2.0 on 2017-12-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_names', models.TextField(blank=True, null=True)),
                ('tag', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('gender', models.BigIntegerField(blank=True, null=True)),
                ('sleep_time', models.BigIntegerField(blank=True, null=True)),
                ('wakeup_time', models.BigIntegerField(blank=True, null=True)),
                ('dos', models.BigIntegerField(blank=True, db_column='DOS', null=True)),
                ('hardsleep', models.BigIntegerField(blank=True, db_column='Hardsleep', null=True)),
                ('slpqua', models.BigIntegerField(blank=True, null=True)),
                ('nap', models.BigIntegerField(blank=True, null=True)),
                ('naptime', models.BigIntegerField(blank=True, null=True)),
                ('cafe', models.BigIntegerField(blank=True, null=True)),
                ('tempam', models.BigIntegerField(blank=True, null=True)),
                ('feelam', models.BigIntegerField(blank=True, null=True)),
                ('mindam', models.BigIntegerField(blank=True, null=True)),
                ('temppm', models.BigIntegerField(blank=True, null=True)),
                ('feelpm', models.BigIntegerField(blank=True, null=True)),
                ('mindpm', models.BigIntegerField(blank=True, null=True)),
                ('cct', models.BigIntegerField(blank=True, null=True)),
                ('cri', models.BigIntegerField(blank=True, null=True)),
                ('lux', models.BigIntegerField(blank=True, null=True)),
                ('caf', models.FloatField(blank=True, null=True)),
                ('q', models.BigIntegerField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('press', models.FloatField(blank=True, db_column='Press', null=True)),
                ('tm', models.FloatField(blank=True, db_column='TM', null=True)),
                ('rh', models.BigIntegerField(blank=True, db_column='RH', null=True)),
                ('ws', models.FloatField(blank=True, db_column='WS', null=True)),
                ('precp', models.BigIntegerField(blank=True, db_column='Precp', null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('temp', models.BigIntegerField(blank=True, null=True)),
                ('co2', models.BigIntegerField(blank=True, db_column='CO2', null=True)),
                ('time_block', models.BigIntegerField(blank=True, db_column='time.block', null=True)),
                ('na', models.TextField(blank=True, db_column='NA', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ques_tb',
            },
        ),
    ]
