# Generated by Django 2.0 on 2017-12-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_restaurantscomment_restaurantsfood_restaurantsrestaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
