# Generated by Django 2.0 on 2018-01-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_djangosession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightTb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('gender', models.BigIntegerField(blank=True, null=True)),
                ('cct', models.BigIntegerField(blank=True, null=True)),
                ('cri', models.BigIntegerField(blank=True, null=True)),
                ('lux', models.BigIntegerField(blank=True, null=True)),
                ('caf', models.FloatField(blank=True, null=True)),
                ('q', models.BigIntegerField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('press', models.FloatField(blank=True, db_column='Press', null=True)),
                ('tm', models.FloatField(blank=True, db_column='TM', null=True)),
                ('rh', models.BigIntegerField(blank=True, db_column='RH', null=True)),
                ('precp', models.FloatField(blank=True, db_column='Precp', null=True)),
                ('humidity', models.BigIntegerField(blank=True, null=True)),
                ('temp', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'light_tb',
                'managed': False,
            },
        ),
    ]
