# Generated by Django 2.0 on 2018-01-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_lighttb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepTb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('gender', models.BigIntegerField(blank=True, null=True)),
                ('st', models.BigIntegerField(blank=True, null=True)),
                ('wt', models.BigIntegerField(blank=True, null=True)),
                ('nap', models.BigIntegerField(blank=True, null=True)),
                ('naptime', models.BigIntegerField(blank=True, null=True)),
                ('cafe', models.BigIntegerField(blank=True, null=True)),
                ('tempam', models.BigIntegerField(blank=True, null=True)),
                ('feelam', models.BigIntegerField(blank=True, null=True)),
                ('mindam', models.BigIntegerField(blank=True, null=True)),
                ('temppm', models.BigIntegerField(blank=True, null=True)),
                ('feelpm', models.BigIntegerField(blank=True, null=True)),
                ('mindpm', models.BigIntegerField(blank=True, null=True)),
                ('q_time', models.TextField(blank=True, null=True)),
                ('dos', models.BigIntegerField(blank=True, db_column='DOS', null=True)),
                ('insomnia', models.BigIntegerField(blank=True, null=True)),
                ('slpqul', models.BigIntegerField(blank=True, null=True)),
                ('cct', models.BigIntegerField(blank=True, null=True)),
                ('cri', models.BigIntegerField(blank=True, null=True)),
                ('lux', models.BigIntegerField(blank=True, null=True)),
                ('caf', models.FloatField(blank=True, null=True)),
                ('q', models.BigIntegerField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('press', models.FloatField(blank=True, db_column='Press', null=True)),
                ('tm', models.FloatField(blank=True, db_column='TM', null=True)),
                ('rh', models.BigIntegerField(blank=True, db_column='RH', null=True)),
                ('precp', models.FloatField(blank=True, db_column='Precp', null=True)),
                ('humidity', models.BigIntegerField(blank=True, null=True)),
                ('temp', models.BigIntegerField(blank=True, null=True)),
                ('time_block', models.TextField(blank=True, db_column='time.block', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sleep_tb',
            },
        ),
    ]
