# Generated by Django 2.0 on 2017-12-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CctBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.TextField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cct_bar',
            },
        ),
        migrations.CreateModel(
            name='FreqComb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.TextField(blank=True, null=True)),
                ('lux', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'freq_comb',
            },
        ),
        migrations.CreateModel(
            name='LuxBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lux', models.TextField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'lux_bar',
            },
        ),
        migrations.CreateModel(
            name='QusCct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.TextField(blank=True, null=True)),
                ('cold', models.FloatField(blank=True, null=True)),
                ('feel', models.FloatField(blank=True, null=True)),
                ('mind', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'qus_cct',
            },
        ),
        migrations.CreateModel(
            name='QusLux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lux', models.TextField(blank=True, null=True)),
                ('cold', models.FloatField(blank=True, null=True)),
                ('feel', models.FloatField(blank=True, null=True)),
                ('mind', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'qus_lux',
            },
        ),
        migrations.CreateModel(
            name='QXyplot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.TextField(blank=True, null=True)),
                ('q', models.TextField(blank=True, null=True)),
                ('cct', models.TextField(blank=True, null=True)),
                ('lux', models.TextField(blank=True, null=True)),
                ('count', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'q_xyplot',
            },
        ),
    ]
